//websrc.js
var bxSites = {bxtapGates:[{'bxgate0':'kuaijifuwu/', cn:'会计'},
        {'bxgate1':'lvshifuwu/', cn:'律师'},
        {'bxgate2':'baoxianfuwu/', cn:'保险'},
        {'bxgate3':'yinshuapenghui/', cn:'印刷包装'},
        {'bxgate4':'penhuizhaopai/', cn:'喷绘招牌'},
        {'bxgate5':'guanggaomeiti/', cn:'媒体广告'},
        {'bxgate6':'sheji/', cn:'设计'},
        {'bxgate7':'wangzhanjianshe/', cn:'网站架设'},
        {'bxgate8':'wangluobuxian/', cn:'网络布线'},
        {'bxgate9':'qingdian/', cn:'庆典相关'},
        {'bxgate10':'zulin/', cn:'租赁'},
        {'bxgate11':'bangongweixiu/', cn:'设备维修'},
        {'bxgate12':'gongyeshebei/', cn:'工业设备'},
        {'bxgate13':'kuaidifuwu/', cn:'快递'},
        {'bxgate14':'nongye/', cn:'农林牧'},
        {'bxgate15':'wupinpifa/', cn:'批发'},
        {'bxgate16':'lipinfuwu/', cn:'礼品定制'},
        {'bxgate17':'canyinmeishi/', cn:'餐饮'},
        {'bxgate18':'daiyunyingtg/', cn:'托管/代运'},
        {'bxgate19':'fanyifuwu/', cn:'翻译'},
        {'bxgate20':'suji/', cn:'速记'},
        {'bxgate21':'jianzhuweixiu/', cn:'建筑维修'}],
    bxtapJobs:[{'bxjob0':'gongren/'},//addr '/' pos-1    //class='preview-hover'
        {'bxjob1':'jixie/'},
        {'bxjob2':'dianzi/'},
        {'bxjob3':'siji/'},
        {'bxjob4':'songhuoyuan/'},
        {'bxjob5':'chushi/'},
        {'bxjob6':'fuwuyuan/'},
        {'bxjob7':'dianyuan/'},
        {'bxjob8':'qichemeirong/'},
        {'bxjob9':'xiaoshou/'},
        {'bxjob10':'fangdichan/'},
        {'bxjob11':'wenmi/'},
        {'bxjob12':'renshi/'},
        {'bxjob13':'kefu/'},
        {'bxjob14':'bangyong/'},
        {'bxjob15':'baojian/'},
        {'bxjob16':'meirongshi/'},
        {'bxjob17':'jianshen/'},
        {'bxjob18':'kuaiji/'},
        {'bxjob19':'jinrong/'},
        {'bxjob20':'baoxianzhaopin/'},
        {'bxjob21':'chengxuyuan/'},
        {'bxjob22':'meigong/'},
        {'bxjob23':'taobaojob/'},
        {'bxjob24':'laoshi/'},
        {'bxjob25':'daoyou/'},
        {'bxjob26':'yinshiyule/'},
        {'bxjob27':'yisheng/'},
        {'bxjob28':'caigou/'},
        {'bxjob29':'shichang/'},
        {'bxjob30':'ktvjiuba/'},
        {'bxjob31':'fanyi/'},
        {'bxjob32':'falv/'},
        {'bxjob33':'nonglinmuyu/'},
        {'bxjob34':'chuguolaowu/'},
        {'bxjob35':'qitazhaopin/'}],
    bxtapServes:[{'bxserve0':'baomu/', cn:'保姆/月嫂'},//addr on middle
        {'bxserve1':'canyin/', cn:'生活配送'},
        {'bxserve2':'wupinhuishou/', cn:'回收'},
        {'bxserve3':'baojieqingxi/', cn:'清洗保洁'},
        {'bxserve4':'xiyihuli/', cn:'洗衣护理'},
        {'bxserve5':'banjia/', cn:'搬家'},
        {'bxserve6':'jiadianweixiu/', cn:'家电维修'},
        {'bxserve7':'fangwuweixiu/', cn:'房屋维护'},
        {'bxserve8':'weixiu/', cn:'管道维修'},
        {'bxserve9':'kaisuo/', cn:'开锁修锁'},
        {'bxserve10':'diannaoweixiu/', cn:'电脑维修'},
        {'bxserve11':'jiadianweixiu/', cn:'家电维修'},
        {'bxserve12':'jiajuweixiu/', cn:'家具维修'},
        {'bxserve13':'jiatingzhuangxiu/', cn:'装修'},
        {'bxserve14':'ruanzhuang/', cn:'装饰'},
        {'bxserve15':'jiancaizhuangshi/', cn:'建材服务'},
        {'bxserve16':'zhuangxiu/', cn:'工装'}],
    bxtapRend:[{'bxrend0':'zhengzu/'},//addr [] on lower
        {'bxrend1':'ershoufang/'},
        {'bxrend2':'duanzu/'},
        {'bxrend3':'jingyingzhuanrang/'},
        {'bxrend4':'shangpuchushou/'},
        {'bxrend5':'shangpu/'},
        {'bxrend6':'shoufang/'},
        {'bxrend7':'changfang/'}],
    bxtapOlds:[{'bxold0':'shouji/'},//class='meta-location' span for water drop
        {'bxold1':'yinger/'},
        {'bxold2':'diannao/'},
        {'bxold3':'dianqi/'},
        {'bxold4':'bijiben/'},
        {'bxold5':'jiaju/'},
        {'bxold6':'pingbandiannao/'},
        {'bxold7':'fushi/'},
        {'bxold8':'shumachanpin/'},
        {'bxold9':'menpiao/'},
        {'bxold10':'zhaoxiangji/'},
        {'bxold11':'riyongpin/'},
        {'bxold12':'shoujipeijian/'},
        {'bxold13':'yundongqicai/'},
        {'bxold14':'shoucang/'},
        {'bxold15':'ershouzixingche/'},
        {'bxold16':'bangongyongpin/'},
        {'bxold17':'bangongjiaju/'},
        {'bxold18':'gongyeshebei/'},
        {'bxold19':'yueqi/'},
        {'bxold20':'qishipenjing/'},
        {'bxold21':'nongchanpin/'},
        {'bxold22':'quanxinshangjia/'},
        {'bxold23':'qitazhuanrang/'},
        {'bxold24':'xuniwupin/'}]}
    , site58s = {tapGates58:[{'58gate0':'shangbiaozhli/', cn:'专利商标'},//id="infolist id="rightframe"
    {'58gate1':'lvshi/', cn:'法律'},
    {'58gate2':'caishui/', cn:'财务会计'},
    {'58gate3':'danbaobaoxiantouzi/', cn:'担保投资'},
    {'58gate4':'baoxianfuwu/', cn:'保险'},
    {'58gate5':'zixunzhongjie/', cn:'咨询'},
    {'58gate6':'huoyun/', cn:'货运物流'},
    {'58gate7':'kuaidi/', cn:'快递'},
    {'58gate8':'wuliu/', cn:'专线货运'},
    {'58gate9':'huojiasheb/', cn:'货架'},
    {'58gate10':'chuanmei/', cn:'传媒广告'},
    {'58gate11':'pingmian/', cn:'设计'},
    {'58gate12':'yinshua/', cn:'包装印刷'},
    {'58gate13':'penhui/', cn:'喷绘招铭牌'},
    {'58gate14':'allzhika/', cn:'制卡'},
    {'58gate15':'lipindingzhi/', cn:'礼品定制'},
    {'58gate16':'fanyi/', cn:'翻译速记'},
    {'58gate17':'wangzhan/', cn:'网站架设'},
    {'58gate18':'xitong/', cn:'网络布线'},
    {'58gate19':'appkaifa/', cn:'app研发'},
    {'58gate20':'wangzhantg/', cn:'网络营销'},
    {'58gate21':'jixieweixiu/', cn:'机械设备维护'},
    {'58gate22':'bgsbwx/', cn:'办公设备维护'},
    {'58gate23':'jianzhuweixiu/', cn:'建筑维护'},
    {'58gate24':'zulin/', cn:'租赁'},
    {'58gate25':'nongjiale/', cn:'农家经营'},
    {'58gate26':'shaokaoy/', cn:'烧烤小吃'},
    {'58gate27':'dujia/', cn:'度假娱乐'},
    {'58gate28':'wenquandujiacun/', cn:'温泉'},
    {'58gate29':'caizhai/', cn:'采摘'},
    {'58gate30':'piaoliuq/', cn:'漂流'},
    {'58gate31':'zuliaoam/', cn:'按摩足疗'},
    {'58gate32':'xiyuzx/', cn:'洗浴温泉'},
    {'58gate33':'jianshen/', cn:'运动健身'},
    {'58gate34':'yulecs/', cn:'台球厅'},
    {'58gate35':'zhuoyouba/', cn:'桌游'},
    {'58gate36':'chaguanxx/', cn:'茶馆'},
    {'58gate37':'kafeit/', cn:'咖啡厅'},
    {'58gate38':'diysgf/', cn:'DIY坊'},
    {'58gate39':'ktv/', cn:'KTV'},
    {'58gate40':'jiuba/', cn:'酒吧夜店'},
    {'58gate41':'wangba/', cn:'网吧'}],
    tapJobs58:[{'58job0':'kefu/'},//id="infolist id="rightframe"
        {'58job1':'renli/'},
        {'58job2':'zplvyoujiudian/'},
        {'58job3':'zpjiudian/'},
        {'58job4':'jiudianzp/'},
        {'58job5':'chaoshishangye/'},
        {'58job6':'meirongjianshen/'},
        {'58job7':'zpanmo/'},
        {'58job8':'zpjianshen/'},
        {'58job9':'zpshengchankaifa/'},
        {'58job10':'zpshengchan/'},
        {'58job11':'zpqiche/'},
        {'58job12':'zpfangchanjianzhu/'},
        {'58job13':'zpwuye/'},
        {'58job14':'zpfangchan/'},
        {'58job15':'jiazhengbaojiexin/'},
        {'58job16':'siji/'},
        {'58job17':'zpshangwumaoyi/'},
        {'58job18':'zpwuliucangchu/'},
        {'58job19':'zptaobao/'},
        {'58job20':'zpmeishu/'},
        {'58job21':'shichang/'},
        {'58job22':'zpwentiyingshi/'},
        {'58job23':'zhuanye/'},
        {'58job24':'zpcaiwushenji/'},
        {'58job25':'zpfalvzixun/'},
        {'58job26':'fanyizhaopin/'},
        {'58job27':'zpxiezuochuban/'},
        {'58job28':'tech/'},
        {'58job29':'zpjixieyiqi/'},
        {'58job30':'zpjixie/'},
        {'58job31':'jinrongtouzi/'},
        {'58job32':'zpjinrongbaoxian/'},
        {'58job33':'zpyiyuanyiliao/'},
        {'58job34':'zpzhiyao/'},
        {'58job35':'xiaofeipin/'},
        {'58job36':'huanbao/'},
        {'58job37':'huagonggy/'},
        {'58job38':'zhikonganfang/'},
        {'58job39':'zpguanli/'},
        {'58job40':'nonglinmuyu/'},
        {'58job41':'dianzi/'}],
    tapServes58:[{'58serve0':'banjia/', cn:'搬家'},//id="infolist id="rightframe"
        {'58serve1':'baomu/', cn:'月嫂保姆'},
        {'58serve2':'baojie/', cn:'清洗保洁'},
        {'58serve3':'huishou/', cn:'回收'},
        {'58serve4':'shutong/', cn:'疏通清洗'},
        {'58serve5':'songshui/', cn:'生活配送'},
        {'58serve6':'kaisuo/', cn:'门锁相关'},
        {'58serve7':'lipinxianhua/', cn:'鲜花植被'},
        {'58serve8':'ganxi/', cn:'衣物护理'},
        {'58serve9':'dianqi/', cn:'家电维修'},
        {'58serve10':'weixiu/', cn:'电脑维修'},
        {'58serve11':'shoujiweixiu/', cn:'手机维修'},
        {'58serve12':'kongtiao/', cn:'空调维修相关'},
        {'58serve13':'shumaweixiu/', cn:'数码维修'},
        {'58serve14':'jiajuweixiu/', cn:'家具维修'}],
    tapRend58:[{'58rend0':'chuzu/'}],//index addr very detailed
    tapOlds58:[{'58old0':'shouji/'},//id="infolist id="rightframe"
        {'58old1':'diannao/'},
        {'58old2':'jiadian/'},
        {'58old3':'ershoujiaju/'},
        {'58old4':'danche/'},
        {'58old5':'zixingche/'},
        {'58old6':'gongcheng/'},
        {'58old7':'zhuangzaiji/'},
        {'58old8':'newchache/'},
        {'58old9':'tuituji/'},
        {'58old10':'yaluji1/'},
        {'58old11':'pingdiji/'},
        {'58old12':'diaoche/'},
        {'58old13':'qzj/'},
        {'58old14':'diaokeji/'},
        {'58old15':'jiagongzhongxin/'},
        {'58old16':'jichuang/'},
        {'58old17':'chongchuang/'},
        {'58old18':'nchechuang/'},
        {'58old19':'jianbanji/'},
        {'58old20':'zhewanji/'},
        {'58old21':'mochuang/'},
        {'58old22':'xichuang/'},
        {'58old23':'qitajichuangshebei/'},
        {'58old24':'chufangshebei/'},
        {'58old25':'jiudianshebei/'},
        {'58old26':'xiaochiche/'},
        {'58old27':'lengdongshebei/'},
        {'58old28':'qiepianji/'},
        {'58old29':'youzhashebei/'},
        {'58old30':'yinliaojiagongshebei/'},
        {'58old31':'hongbeishebei/'},
        {'58old32':'roujiagongshebei/'},
        {'58old33':'shipinjiaobanshebei/'},
        {'58old34':'guoshujiagongshebei/'},
        {'58old35':'qitashipinjiagongjixie/'},
        {'58old36':'jiguangdabiaoji/'},
        {'58old37':'xiezhenji/'},
        {'58old38':'yinshuaji/'},
        {'58old39':'jiguangqiegeji/'},
        {'58old40':'qitayinshuashebei/'},
        {'58old41':'fenglfaadianshebei/'},
        {'58old42':'nfadianji/'},
        {'58old43':'fadianjizu/'},
        {'58old44':'chaiyoufadianshebei/'},
        {'58old45':'bianyaqiq/'},
        {'58old46':'kongyaji/'},
        {'58old47':'qiyoufadianshebei/'},
        {'58old48':'qitafadianshebei/'},
        {'58old49':'zhusuji/'},
        {'58old50':'fensuiji/'},
        {'58old51':'fengkouji/'},
        {'58old52':'chengxingji/'},
        {'58old53':'hanji/'},
        {'58old54':'qitasuliaoshebei/'},
        {'58old55':'lixinji/'},
        {'58old56':'fanyingfu/'},
        {'58old57':'ganzaoji/'},
        {'58old58':'jiaobanjis/'},
        {'58old59':'guolvqi/'},
        {'58old60':'qitahuagongshebei/'},
        {'58old61':'fenxiy/'},
        {'58old62':'jianceyi/'},
        {'58old63':'dibangg/'},
        {'58old64':'qitayiqiyibiao/'},
        {'58old65':'yumijiagong/'},
        {'58old66':'dabaoji/'},
        {'58old67':'shougeji/'},
        {'58old68':'qitanongyongjixie/'}]}
    , nations = [{bx:'beijing', tc:'bj', cn:'北京市'},
    {bx:'shanghai', tc:'sh', cn:'上海市'},
    {bx:'tianjin', tc:'tj', cn:'天津市'},
    {bx:'chongqing', tc:'cq', cn:'重庆市'},
    {bx:'hebei', tc:'', cn:'河北省'},
    {bx:'handan', tc:'hd', cn:'邯郸市'},
    {bx:'shijiazhuang', tc:'sjz', cn:'石家庄市'},
    {bx:'baoding', tc:'bd', cn:'保定市'},
    {bx:'zhangjiakou', tc:'zjk', cn:'张家口市'},
    {bx:'', tc:'dingzhou', cn:'定州市'},
    {bx:'', tc:'gt', cn:'馆陶市'},
    {bx:'', tc:'zhangbei', cn:'张北市'},
    {bx:'', tc:'zx', cn:'赵县市'},
    {bx:'', tc:'zd', cn:'正定市'},
    {bx:'', tc:'linyixian', cn:'临猗市'},
    {bx:'', tc:'qingxu', cn:'清徐市'},
    {bx:'anshan', tc:'as', cn:'鞍山市'},
    {bx:'fushun', tc:'fushun', cn:'抚顺市'},
    {bx:'benxi', tc:'', cn:'本溪市'},
    {bx:'dandong', tc:'dandong', cn:'丹东市'},
    {bx:'jinzhou', tc:'jinzhou', cn:'锦州市'},
    {bx:'yingkou', tc:'yk', cn:'营口市'},
    {bx:'fuxin', tc:'', cn:'阜新市'},
    {bx:'liaoyang', tc:'liaoyang', cn:'辽阳市'},
    {bx:'chaoyang', tc:'cy', cn:'朝阳市'},
    {bx:'panjin', tc:'pj', cn:'盘锦市'},
    {bx:'huludao', tc:'hld', cn:'葫芦岛市'},
    {bx:'jilinn', tc:'', cn:'吉林省'},
    {bx:'changchun', tc:'cc', cn:'长春市'},
    {bx:'jilin', tc:'jl', cn:'吉林市'},
    {bx:'yanbian', tc:'yanbian', cn:'延边市'},
    {bx:'siping', tc:'sp', cn:'四平市'},
    {bx:'tonghua', tc:'th', cn:'通化市'},
    {bx:'baicheng', tc:'bc', cn:'白城市'},
    {bx:'liaoyuan', tc:'liaoyuan', cn:'辽源市'},
    {bx:'songyuan', tc:'songyuan', cn:'松原市'},
    {bx:'baishan', tc:'baishan', cn:'白山市'},
    {bx:'heilongjiang', tc:'', cn:'黑龙江省'},
    {bx:'jixi', tc:'jixi', cn:'鸡西市'},
    {bx:'qitaihe', tc:'qth', cn:'七台河市'},
    {bx:'hegang', tc:'hegang', cn:'鹤岗市'},
    {bx:'shuangyashan', tc:'sys', cn:'双鸭山市'},
    {bx:'yichun', tc:'yich', cn:'伊春市'},
    {bx:'haerbin', tc:'hrb', cn:'哈尔滨市'},
    {bx:'qiqihaer', tc:'qqhr', cn:'齐齐哈尔市'},
    {bx:'mudanjiang', tc:'mdj', cn:'牡丹江市'},
    {bx:'jiamusi', tc:'jms', cn:'佳木斯市'},
    {bx:'heihe', tc:'heihe', cn:'黑河市'},
    {bx:'suihua', tc:'suihua', cn:'绥化市'},
    {bx:'daqing', tc:'dq', cn:'大庆市'},
    {bx:'daxinganling', tc:'dxal', cn:'大兴安岭市'},
    {bx:'jiangsu', tc:'', cn:'江苏省'},
    {bx:'nanjing', tc:'nj', cn:'南京市'},
    {bx:'wuxi', tc:'wx', cn:'无锡市'},
    {bx:'zhenjiang', tc:'zj', cn:'镇江市'},
    {bx:'suzhou', tc:'su', cn:'苏州市'},
    {bx:'nantong', tc:'nt', cn:'南通市'},
    {bx:'yangzhou', tc:'yz', cn:'扬州市'},
    {bx:'yancheng', tc:'yancheng', cn:'盐城市'},
    {bx:'xuzhou', tc:'xz', cn:'徐州市'},
    {bx:'huaian', tc:'ha', cn:'淮安市'},
    {bx:'lianyungang', tc:'lyg', cn:'连云港市'},
    {bx:'', tc:'qidong', cn:'启东市'},
    {bx:'', tc:'liyang', cn:'溧阳市'},
    {bx:'', tc:'haimen', cn:'海门市'},
    {bx:'', tc:'donghai', cn:'东海市'},
    {bx:'', tc:'yangzhong', cn:'扬中市'},
    {bx:'', tc:'xinghuashi', cn:'兴化市'},
    {bx:'', tc:'xinyishi', cn:'新沂市'},
    {bx:'', tc:'taixing', cn:'泰兴市'},
    {bx:'', tc:'rudong', cn:'如东市'},
    {bx:'', tc:'pizhou', cn:'邳州市'},
    {bx:'', tc:'xzpeixian', cn:'沛县市'},
    {bx:'', tc:'jingjiang', cn:'靖江市'},
    {bx:'', tc:'jianhu', cn:'建湖市'},
    {bx:'', tc:'haian', cn:'海安市'},
    {bx:'', tc:'dongtai', cn:'东台市'},
    {bx:'', tc:'danyang', cn:'丹阳市'},
    {bx:'changzhou', tc:'cz', cn:'常州市'},
    {bx:'tz', tc:'taizhou', cn:'泰州市'},
    {bx:'suqian', tc:'suqian', cn:'宿迁市'},
    {bx:'kunshan', tc:'', cn:'昆山市'},
    {bx:'changshu', tc:'', cn:'常熟市'},
    {bx:'zhangjiagang', tc:'', cn:'张家港市'},
    {bx:'taicang', tc:'', cn:'太仓市'},
    {bx:'', tc:'dafeng', cn:'大丰市'},
    {bx:'', tc:'rugao', cn:'如皋市'},
    {bx:'zhejiang', tc:'', cn:'浙江省'},
    {bx:'', tc:'yueqingcity', cn:'乐清市'},
    {bx:'', tc:'ruiancity', cn:'瑞安市'},
    {bx:'', tc:'yiwu', cn:'义乌市'},
    {bx:'', tc:'yuyao', cn:'余姚市'},
    {bx:'', tc:'zhuji', cn:'诸暨市'},
    {bx:'', tc:'xiangshanxian', cn:'象山市'},
    {bx:'', tc:'wenling', cn:'温岭市'},
    {bx:'', tc:'tongxiang', cn:'桐乡市'},
    {bx:'', tc:'cixi', cn:'慈溪市'},
    {bx:'', tc:'changxing', cn:'长兴市'},
    {bx:'', tc:'jiashanx', cn:'嘉善市'},
    {bx:'', tc:'haining', cn:'海宁市'},
    {bx:'', tc:'deqing', cn:'德清市'},
    {bx:'chengde', tc:'chengde', cn:'承德市'},
    {bx:'tangshan', tc:'ts', cn:'唐山市'},
    {bx:'langfang', tc:'lf', cn:'廊坊市'},
    {bx:'cangzhou', tc:'cangzhou', cn:'沧州市'},
    {bx:'hengshui', tc:'hs', cn:'衡水市'},
    {bx:'xingtai', tc:'xt', cn:'邢台市'},
    {bx:'qinhuangdao', tc:'qhd', cn:'秦皇岛市'},
    {bx:'shanxi', tc:'', cn:'山西省'},
    {bx:'shuozhou', tc:'shuozhou', cn:'朔州市'},
    {bx:'xinzhou', tc:'xinzhou', cn:'忻州市'},
    {bx:'taiyuan', tc:'ty', cn:'太原市'},
    {bx:'datong', tc:'dt', cn:'大同市'},
    {bx:'yangquan', tc:'yq', cn:'阳泉市'},
    {bx:'jinzhong', tc:'jz', cn:'晋中市'},
    {bx:'changzhi', tc:'changzhi', cn:'长治市'},
    {bx:'jincheng', tc:'jincheng', cn:'晋城市'},
    {bx:'linfen', tc:'linfen', cn:'临汾市'},
    {bx:'lvliang', tc:'lvliang', cn:'吕梁市'},
    {bx:'yuncheng', tc:'yuncheng', cn:'运城市'},
    {bx:'neimenggu', tc:'', cn:'内蒙古自治区'},
    {bx:'hulunbeier', tc:'hlbe', cn:'呼伦贝尔市'},
    {bx:'huhehaote', tc:'hu', cn:'呼和浩特市'},
    {bx:'baotou', tc:'bt', cn:'包头市'},
    {bx:'wuhai', tc:'wuhai', cn:'乌海市'},
    {bx:'wulanchabu', tc:'wlcb', cn:'乌兰察布市'},
    {bx:'tongliao', tc:'tongliao', cn:'通辽市'},
    {bx:'chifeng', tc:'chifeng', cn:'赤峰市'},
    {bx:'eerduosi', tc:'erds', cn:'鄂尔多斯市'},
    {bx:'bayannaoer', tc:'bycem', cn:'巴彦淖尔市'},
    {bx:'xilinguole', tc:'xl', cn:'锡林郭勒市'},
    {bx:'xingan', tc:'xam', cn:'兴安市'},
    {bx:'alashan', tc:'alsm', cn:'阿拉善市'},
    {bx:'liaoning', tc:'', cn:'辽宁省'},
    {bx:'shenyang', tc:'sy', cn:'沈阳市'},
    {bx:'tieling', tc:'tl', cn:'铁岭市'},
    {bx:'dalian', tc:'dl', cn:'大连市'},
    {bx:'', tc:'yxx', cn:'永新市'},
    {bx:'', tc:'pld', cn:'庄河市'},
    {bx:'', tc:'wfd', cn:'瓦房店市'},
    {bx:'quzhou', tc:'quzhou', cn:'衢州市'},
    {bx:'hangzhou', tc:'hz', cn:'杭州市'},
    {bx:'huzhou', tc:'huzhou', cn:'湖州市'},
    {bx:'jiaxing', tc:'jx', cn:'嘉兴市'},
    {bx:'ningbo', tc:'nb', cn:'宁波市'},
    {bx:'shaoxing', tc:'sx', cn:'绍兴市'},
    {bx:'taizhou', tc:'tz', cn:'台州市'},
    {bx:'wenzhou', tc:'wz', cn:'温州市'},
    {bx:'lishui', tc:'lishui', cn:'丽水市'},
    {bx:'jinhua', tc:'jh', cn:'金华市'},
    {bx:'zhoushan', tc:'zhoushan', cn:'舟山市'},
    {bx:'anhui', tc:'', cn:'安徽省'},
    {bx:'chuzhou', tc:'chuzhou', cn:'滁州市'},
    {bx:'fuyang', tc:'fy', cn:'阜阳市'},
    {bx:'hefei', tc:'hf', cn:'合肥市'},
    {bx:'bengbu', tc:'bengbu', cn:'蚌埠市'},
    {bx:'wuhu', tc:'wuhu', cn:'芜湖市'},
    {bx:'huainan', tc:'hn', cn:'淮南市'},
    {bx:'maanshan', tc:'mas', cn:'马鞍山市'},
    {bx:'anqing', tc:'anqing', cn:'安庆市'},
    {bx:'sz', tc:'suzhou', cn:'宿州市'},
    {bx:'bozhou', tc:'bozhou', cn:'亳州市'},
    {bx:'huangshan', tc:'huangshan', cn:'黄山市'},
    {bx:'huaibei', tc:'huaibei', cn:'淮北市'},
    {bx:'tongling', tc:'tongling', cn:'铜陵市'},
    {bx:'xuancheng', tc:'xuancheng', cn:'宣城市'},
    {bx:'luan', tc:'la', cn:'六安市'},
    {bx:'', tc:'hexian', cn:'和县市'},
    {bx:'', tc:'hq', cn:'霍邱市'},
    {bx:'', tc:'tongcheng', cn:'桐城市'},
    {bx:'', tc:'ningguo', cn:'宁国市'},
    {bx:'', tc:'tianchang', cn:'天长市'},
    {bx:'chaohu', tc:'ch', cn:'巢湖市'},
    {bx:'chizhou', tc:'chizhou', cn:'池州市'},
    {bx:'shandong', tc:'', cn:'山东省'},
    {bx:'taian', tc:'ta', cn:'泰安市'},
    {bx:'heze', tc:'heze', cn:'菏泽市'},
    {bx:'jinan', tc:'jn', cn:'济南市'},
    {bx:'qingdao', tc:'qd', cn:'青岛市'},
    {bx:'zibo', tc:'zb', cn:'淄博市'},
    {bx:'dezhou', tc:'dz', cn:'德州市'},
    {bx:'yantai', tc:'yt', cn:'烟台市'},
    {bx:'weifang', tc:'wf', cn:'潍坊市'},
    {bx:'jining', tc:'jining', cn:'济宁市'},
    {bx:'weihai', tc:'weihai', cn:'威海市'},
    {bx:'linyi', tc:'linyi', cn:'临沂市'},
    {bx:'binzhou', tc:'binzhou', cn:'滨州市'},
    {bx:'dongying', tc:'dy', cn:'东营市'},
    {bx:'zaozhuang', tc:'zaozhuang', cn:'枣庄市'},
    {bx:'rizhao', tc:'rizhao', cn:'日照市'},
    {bx:'', tc:'zhangqiu', cn:'章丘市'},
    {bx:'', tc:'zc', cn:'诸城市'},
    {bx:'', tc:'shouguang', cn:'寿光市'},
    {bx:'', tc:'shuyang', cn:'沭阳市'},
    {bx:'laiwu', tc:'lw', cn:'莱芜市'},
    {bx:'liaocheng', tc:'lc', cn:'聊城市'},
    {bx:'henan', tc:'', cn:'河南省'},
    {bx:'shangqiu', tc:'sq', cn:'商丘市'},
    {bx:'zhengzhou', tc:'zz', cn:'郑州市'},
    {bx:'anyang', tc:'ay', cn:'安阳市'},
    {bx:'xinxiang', tc:'xx', cn:'新乡市'},
    {bx:'xuchang', tc:'xc', cn:'许昌市'},
    {bx:'pingdingshan', tc:'pds', cn:'平顶山市'},
    {bx:'xinyang', tc:'xy', cn:'信阳市'},
    {bx:'nanyang', tc:'ny', cn:'南阳市'},
    {bx:'kaifeng', tc:'kaifeng', cn:'开封市'},
    {bx:'luoyang', tc:'luoyang', cn:'洛阳市'},
    {bx:'jiaozuo', tc:'jiaozuo', cn:'焦作市'},
    {bx:'hebi', tc:'hb', cn:'鹤壁市'},
    {bx:'puyang', tc:'puyang', cn:'濮阳市'},
    {bx:'zhoukou', tc:'zk', cn:'周口市'},
    {bx:'luohe', tc:'luohe', cn:'漯河市'},
    {bx:'zhumadian', tc:'zmd', cn:'驻马店市'},
    {bx:'sanmenxia', tc:'smx', cn:'三门峡市'},
    {bx:'jiyuan', tc:'jiyuan', cn:'济源市'},
    {bx:'hunan', tc:'', cn:'湖南省'},
    {bx:'yueyang', tc:'yy', cn:'岳阳市'},
    {bx:'changsha', tc:'cs', cn:'长沙市'},
    {bx:'xiangtan', tc:'xiangtan', cn:'湘潭市'},
    {bx:'zhuzhou', tc:'zhuzhou', cn:'株洲市'},
    {bx:'hengyang', tc:'hy', cn:'衡阳市'},
    {bx:'chenzhou', tc:'chenzhou', cn:'郴州市'},
    {bx:'changde', tc:'changde', cn:'常德市'},
    {bx:'yiyang', tc:'yiyang', cn:'益阳市'},
    {bx:'loudi', tc:'ld', cn:'娄底市'},
    {bx:'shaoyang', tc:'shaoyang', cn:'邵阳市'},
    {bx:'xiangxi', tc:'xiangxi', cn:'湘西市'},
    {bx:'zhangjiajie', tc:'zjj', cn:'张家界市'},
    {bx:'huaihua', tc:'hh', cn:'怀化市'},
    {bx:'yongzhou', tc:'yongzhou', cn:'永州市'},
    {bx:'hubei', tc:'', cn:'湖北省'},
    {bx:'wuhan', tc:'wh', cn:'武汉市'},
    {bx:'xiantao', tc:'xiantao', cn:'仙桃市'},
    {bx:'tianmen', tc:'tm', cn:'天门市'},
    {bx:'qianjiang', tc:'qianjiang', cn:'潜江市'},
    {bx:'xiangfan', tc:'xf', cn:'襄阳市'},
    {bx:'ezhou', tc:'ez', cn:'鄂州市'},
    {bx:'xiaogan', tc:'xiaogan', cn:'孝感市'},
    {bx:'huanggang', tc:'hg', cn:'黄冈市'},
    {bx:'huangshi', tc:'hshi', cn:'黄石市'},
    {bx:'xianning', tc:'xianning', cn:'咸宁市'},
    {bx:'jingzhou', tc:'jingzhou', cn:'荆州市'},
    {bx:'yichang', tc:'yc', cn:'宜昌市'},
    {bx:'shiyan', tc:'shiyan', cn:'十堰市'},
    {bx:'suizhou', tc:'suizhou', cn:'随州市'},
    {bx:'jingmen', tc:'jingmen', cn:'荆门市'},
    {bx:'enshi', tc:'es', cn:'恩施市'},
    {bx:'shennongjia', tc:'snj', cn:'神农架市'},
    {bx:'', tc:'mg', cn:'明港市'},
    {bx:'', tc:'yanling', cn:'鄢陵市'},
    {bx:'', tc:'yuzhou', cn:'禹州市'},
    {bx:'', tc:'changge', cn:'长葛市'},
    {bx:'', tc:'yidou', cn:'宜都市'},
    {bx:'jiangxi', tc:'', cn:'江西省'},
    {bx:'yingtan', tc:'yingtan', cn:'鹰潭市'},
    {bx:'xinyu', tc:'xinyu', cn:'新余市'},
    {bx:'nanchang', tc:'nc', cn:'南昌市'},
    {bx:'jiujiang', tc:'jj', cn:'九江市'},
    {bx:'shangrao', tc:'sr', cn:'上饶市'},
    {bx:'fz', tc:'fuzhou', cn:'抚州市'},
    {bx:'yc', tc:'yichun', cn:'宜春市'},
    {bx:'jian', tc:'ja', cn:'吉安市'},
    {bx:'ganzhou', tc:'ganzhou', cn:'赣州市'},
    {bx:'jingdezhen', tc:'jdz', cn:'景德镇市'},
    {bx:'pingxiang', tc:'px', cn:'萍乡市'},
    {bx:'fujian', tc:'', cn:'福建省'},
    {bx:'fuzhou', tc:'fz', cn:'福州市'},
    {bx:'xiamen', tc:'xm', cn:'厦门市'},
    {bx:'ningde', tc:'nd', cn:'宁德市'},
    {bx:'putian', tc:'pt', cn:'莆田市'},
    {bx:'quanzhou', tc:'qz', cn:'泉州市'},
    {bx:'zhangzhou', tc:'zhangzhou', cn:'漳州市'},
    {bx:'longyan', tc:'ly', cn:'龙岩市'},
    {bx:'sanming', tc:'sm', cn:'三明市'},
    {bx:'nanping', tc:'np', cn:'南平市'},
    {bx:'guangdong', tc:'', cn:'广东省'},
    {bx:'guangzhou', tc:'gz', cn:'广州市'},
    {bx:'shanwei', tc:'sw', cn:'汕尾市'},
    {bx:'yangjiang', tc:'yj', cn:'阳江市'},
    {bx:'jieyang', tc:'jy', cn:'揭阳市'},
    {bx:'maoming', tc:'mm', cn:'茂名市'},
    {bx:'jiangmen', tc:'jm', cn:'江门市'},
    {bx:'shaoguan', tc:'sg', cn:'韶关市'},
    {bx:'huizhou', tc:'huizhou', cn:'惠州市'},
    {bx:'meizhou', tc:'mz', cn:'梅州市'},
    {bx:'shantou', tc:'st', cn:'汕头市'},
    {bx:'shenzhen', tc:'sz', cn:'深圳市'},
    {bx:'zhuhai', tc:'zh', cn:'珠海市'},
    {bx:'foshan', tc:'fs', cn:'佛山市'},
    {bx:'zhaoqing', tc:'zq', cn:'肇庆市'},
    {bx:'zhanjiang', tc:'zhanjiang', cn:'湛江市'},
    {bx:'zhongshan', tc:'zs', cn:'中山市'},
    {bx:'heyuan', tc:'heyuan', cn:'河源市'},
    {bx:'qingyuan', tc:'qingyuan', cn:'清远市'},
    {bx:'yunfu', tc:'yf', cn:'云浮市'},
    {bx:'chaozhou', tc:'chaozhou', cn:'潮州市'},
    {bx:'', tc:'wuyishan', cn:'武夷山市'},
    {bx:'', tc:'shishi', cn:'石狮市'},
    {bx:'', tc:'jinjiangshi', cn:'晋江市'},
    {bx:'', tc:'nananshi', cn:'南安市'},
    {bx:'dongguan', tc:'dg', cn:'东莞市'},
    {bx:'', tc:'taishan', cn:'台山市'},
    {bx:'', tc:'yangchun', cn:'阳春市'},
    {bx:'', tc:'sd', cn:'顺德市'},
    {bx:'', tc:'huidong', cn:'惠东市'},
    {bx:'', tc:'boluo', cn:'博罗市'},
    {bx:'guangxi', tc:'', cn:'广西壮族自治区'},
    {bx:'laibin', tc:'lb', cn:'来宾市'},
    {bx:'hezhou', tc:'hezhou', cn:'贺州市'},
    {bx:'chongzuo', tc:'chongzuo', cn:'崇左市'},
    {bx:'yl', tc:'yulin', cn:'玉林市'},
    {bx:'fangchenggang', tc:'fcg', cn:'防城港市'},
    {bx:'nanning', tc:'nn', cn:'南宁市'},
    {bx:'liuzhou', tc:'liuzhou', cn:'柳州市'},
    {bx:'guilin', tc:'gl', cn:'桂林市'},
    {bx:'wuzhou', tc:'wuzhou', cn:'梧州市'},
    {bx:'guigang', tc:'gg', cn:'贵港市'},
    {bx:'bose', tc:'baise', cn:'百色市'},
    {bx:'qinzhou', tc:'qinzhou', cn:'钦州市'},
    {bx:'hechi', tc:'hc', cn:'河池市'},
    {bx:'beihai', tc:'bh', cn:'北海市'},
    {bx:'hannan', tc:'', cn:'海南省'},
    {bx:'sanya', tc:'sanya', cn:'三亚市'},
    {bx:'danzhou', tc:'danzhou', cn:'儋州市'},
    {bx:'dongfang', tc:'df', cn:'东方市'},
    {bx:'wenchang', tc:'wenchang', cn:'文昌市'},
    {bx:'qionghai', tc:'qh', cn:'琼海市'},
    {bx:'wuzhishan', tc:'wzs', cn:'五指山市'},
    {bx:'wanning', tc:'wanning', cn:'万宁市'},
    {bx:'haikou', tc:'haikou', cn:'海口市'},
    {bx:'baisha', tc:'baisha', cn:'白沙市'},
    {bx:'sansha', tc:'sansha', cn:'三沙市'},
    {bx:'baoting', tc:'baoting', cn:'保亭市'},
    {bx:'changjiang', tc:'', cn:'昌江市'},
    {bx:'chengmai', tc:'cm', cn:'澄迈市'},
    {bx:'dingan', tc:'da', cn:'定安市'},
    {bx:'ledong', tc:'', cn:'乐东市'},
    {bx:'lingao', tc:'', cn:'临高市'},
    {bx:'lingshui', tc:'lingshui', cn:'陵水市'},
    {bx:'qiongzhong', tc:'qiongzhong', cn:'琼中市'},
    {bx:'tunchang', tc:'tunchang', cn:'屯昌市'},
    {bx:'sichuan', tc:'', cn:'四川省'},
    {bx:'chengdu', tc:'cd', cn:'成都市'},
    {bx:'meishan', tc:'ms', cn:'眉山市'},
    {bx:'ziyang', tc:'zy', cn:'资阳市'},
    {bx:'panzhihua', tc:'panzhihua', cn:'攀枝花市'},
    {bx:'zigong', tc:'zg', cn:'自贡市'},
    {bx:'mianyang', tc:'mianyang', cn:'绵阳市'},
    {bx:'nanchong', tc:'nanchong', cn:'南充市'},
    {bx:'dazhou', tc:'dazhou', cn:'达州市'},
    {bx:'suining', tc:'', cn:'遂宁市'},
    {bx:'guangan', tc:'ga', cn:'广安市'},
    {bx:'bazhong', tc:'bazhong', cn:'巴中市'},
    {bx:'luzhou', tc:'luzhou', cn:'泸州市'},
    {bx:'yibin', tc:'yb', cn:'宜宾市'},
    {bx:'neijiang', tc:'scnj', cn:'内江市'},
    {bx:'leshan', tc:'ls', cn:'乐山市'},
    {bx:'liangshan', tc:'liangshan', cn:'凉山市'},
    {bx:'yaan', tc:'ya', cn:'雅安市'},
    {bx:'ganzi', tc:'ganzi', cn:'甘孜市'},
    {bx:'aba', tc:'ab', cn:'阿坝市'},
    {bx:'deyang', tc:'deyang', cn:'德阳市'},
    {bx:'guangyuan', tc:'guangyuan', cn:'广元市'},
    {bx:'guizhou', tc:'', cn:'贵州省'},
    {bx:'guiyang', tc:'gy', cn:'贵阳市'},
    {bx:'zunyi', tc:'zunyi', cn:'遵义市'},
    {bx:'anshun', tc:'anshun', cn:'安顺市'},
    {bx:'qiannan', tc:'qn', cn:'黔南市'},
    {bx:'qiandongnan', tc:'qdn', cn:'黔东南市'},
    {bx:'tongren', tc:'tr', cn:'铜仁市'},
    {bx:'bijie', tc:'bijie', cn:'毕节市'},
    {bx:'liupanshui', tc:'lps', cn:'六盘水市'},
    {bx:'qianxinan', tc:'qxn', cn:'黔西南市'},
    {bx:'yunnan', tc:'', cn:'云南省'},
    {bx:'xishuangbanna', tc:'bn', cn:'西双版纳市'},
    {bx:'dehong', tc:'dh', cn:'德宏市'},
    {bx:'zhaotong', tc:'zt', cn:'昭通市'},
    {bx:'kunming', tc:'km', cn:'昆明市'},
    {bx:'dali', tc:'dali', cn:'大理市'},
    {bx:'honghe', tc:'honghe', cn:'红河市'},
    {bx:'qujing', tc:'qj', cn:'曲靖市'},
    {bx:'baoshan', tc:'bs', cn:'保山市'},
    {bx:'wenshan', tc:'ws', cn:'文山市'},
    {bx:'yuxi', tc:'yx', cn:'玉溪市'},
    {bx:'chuxiong', tc:'cx', cn:'楚雄市'},
    {bx:'puer', tc:'pe', cn:'普洱市'},
    {bx:'lincang', tc:'lincang', cn:'临沧市'},
    {bx:'nujiang', tc:'nujiang', cn:'怒江市'},
    {bx:'diqing', tc:'diqing', cn:'迪庆市'},
    {bx:'lijiang', tc:'lj', cn:'丽江市'},
    {bx:'xizang', tc:'', cn:'西藏自治区'},
    {bx:'lasa', tc:'lasa', cn:'拉萨市'},
    {bx:'rikaze', tc:'rkz', cn:'日喀则市'},
    {bx:'shannan', tc:'sn', cn:'山南市'},
    {bx:'linzhi', tc:'linzhi', cn:'林芝市'},
    {bx:'changdu', tc:'changdu', cn:'昌都市'},
    {bx:'naqu', tc:'nq', cn:'那曲市'},
    {bx:'ali', tc:'al', cn:'阿里市'},
    {bx:'', tc:'rituxian', cn:'日土市'},
    {bx:'', tc:'gaizexian', cn:'改则市'},
    {bx:'', tc:'hlr', cn:'海拉尔市'},
    {bx:'shaanxi', tc:'', cn:'陕西省'},
    {bx:'xian', tc:'xa', cn:'西安市'},
    {bx:'xianyang', tc:'xianyang', cn:'咸阳市'},
    {bx:'yanan', tc:'yanan', cn:'延安市'},
    {bx:'yulin', tc:'yl', cn:'榆林市'},
    {bx:'weinan', tc:'wn', cn:'渭南市'},
    {bx:'shangluo', tc:'sl', cn:'商洛市'},
    {bx:'ankang', tc:'ankang', cn:'安康市'},
    {bx:'hanzhong', tc:'hanzhong', cn:'汉中市'},
    {bx:'baoji', tc:'baoji', cn:'宝鸡市'},
    {bx:'tongchuan', tc:'tc', cn:'铜川市'},
    {bx:'gansu', tc:'', cn:'甘肃省'},
    {bx:'longnan', tc:'ln', cn:'陇南市'},
    {bx:'wuwei', tc:'wuwei', cn:'武威市'},
    {bx:'jiayuguan', tc:'jyg', cn:'嘉峪关市'},
    {bx:'linxia', tc:'linxia', cn:'临夏市'},
    {bx:'lanzhou', tc:'lz', cn:'兰州市'},
    {bx:'dingxi', tc:'dx', cn:'定西市'},
    {bx:'pingliang', tc:'pl', cn:'平凉市'},
    {bx:'qingyang', tc:'qingyang', cn:'庆阳市'},
    {bx:'jinchang', tc:'jinchang', cn:'金昌市'},
    {bx:'zhangye', tc:'zhangye', cn:'张掖市'},
    {bx:'jiuquan', tc:'jq', cn:'酒泉市'},
    {bx:'tianshui', tc:'tianshui', cn:'天水市'},
    {bx:'gannan', tc:'gn', cn:'甘南市'},
    {bx:'baiyin', tc:'by', cn:'白银市'},
    {bx:'qinghai', tc:'', cn:'青海省'},
    {bx:'haibei', tc:'haibei', cn:'海北市'},
    {bx:'xining', tc:'xn', cn:'西宁市'},
    {bx:'haidong', tc:'haidong', cn:'海东市'},
    {bx:'huangnan', tc:'huangnan', cn:'黄南市'},
    {bx:'guoluo', tc:'guoluo', cn:'果洛市'},
    {bx:'yushu', tc:'ys', cn:'玉树市'},
    {bx:'haixi', tc:'hx', cn:'海西市'},
    {bx:'hainan', tc:'hainan', cn:'海南市'},
    {bx:'ningxia', tc:'', cn:'宁夏回族自治区'},
    {bx:'zhongwei', tc:'zw', cn:'中卫市'},
    {bx:'yinchuan', tc:'yinchuan', cn:'银川市'},
    {bx:'shizuishan', tc:'szs', cn:'石嘴山市'},
    {bx:'wuzhong', tc:'wuzhong', cn:'吴忠市'},
    {bx:'guyuan', tc:'guyuan', cn:'固原市'},
    {bx:'xinjiang', tc:'', cn:'新疆维吾尔自治区'},
    {bx:'yili', tc:'yili', cn:'伊犁市'},
    {bx:'tacheng', tc:'tac', cn:'塔城市'},
    {bx:'hami', tc:'hami', cn:'哈密市'},
    {bx:'hetian', tc:'ht', cn:'和田市'},
    {bx:'aletai', tc:'alt', cn:'阿勒泰市'},
    {bx:'boertala', tc:'betl', cn:'博尔塔拉市'},
    {bx:'kelamayi', tc:'klmy', cn:'克拉玛依市'},
    {bx:'wulumuqi', tc:'xj', cn:'乌鲁木齐市'},
    {bx:'shihezi', tc:'shz', cn:'石河子市'},
    {bx:'changji', tc:'changji', cn:'昌吉市'},
    {bx:'changji', tc:'kl', cn:'垦利市'},
    {bx:'tulufan', tc:'tlf', cn:'吐鲁番市'},
    {bx:'bayinguoleng', tc:'bygl', cn:'巴音郭楞市'},
    {bx:'akesu', tc:'aks', cn:'阿克苏市'},
    {bx:'', tc:'ks', cn:'喀什市'},
    {bx:'', tc:'kzls', cn:'克孜勒苏市'},
    {bx:'', tc:'ale', cn:'阿拉尔市'},
    {bx:'', tc:'wjq', cn:'五家渠市'},
    {bx:'', tc:'tmsk', cn:'图木舒克市'},
    {bx:'', tc:'kel', cn:'库尔勒市'}]

module.exports = {
    bxChildSite: bxSites,
    ChildSite58: site58s,
    qgcitys: nations
}

